"""Deterministic random batch token-budget distribution package."""

from .allocator import AllocationConfig, allocate_hierarchical_tokens
from .batch import (
    BudgetDeductions,
    build_batch_plan,
    build_eligible_frame,
    calculate_batch_budget,
    resolve_batch_window,
)
from .checkpoint import (
    BatchCheckpoint,
    CheckpointCASConflictError,
    CheckpointTransitionError,
    FenceRejectedError,
    JsonCheckpointStore,
    JsonReferenceStore,
    Lease,
    LeaseConflictError,
)
from .models import (
    AllocationNode,
    AllocationResult,
    BatchBudget,
    BatchPlan,
    BatchWindow,
    EligibleFrame,
    ExecutionScheduleEntry,
    FairnessState,
    SelectionRecord,
    SelectionResult,
    SessionDemand,
    TenantAgentKey,
    stable_sha256_hex,
)
from .pacing import Reservation, RollingTokenPacer, UnpaceableReservationError, reserve_with_claim
from .selection import AgentSelectionGrant, select_within_agent_grants, stable_rank_hash
from .simulation import (
    POLICIES,
    SimulationMetric,
    SimulationResult,
    SimulationScenario,
    simulate_policies,
)
from .telemetry import BatchTelemetry, build_batch_telemetry, jain_fairness

__all__ = [
    "AllocationConfig",
    "AllocationNode",
    "AllocationResult",
    "AgentSelectionGrant",
    "BatchBudget",
    "BatchCheckpoint",
    "BatchPlan",
    "BatchTelemetry",
        "CheckpointCASConflictError",
        "CheckpointTransitionError",
    "BatchWindow",
    "BudgetDeductions",
    "EligibleFrame",
    "ExecutionScheduleEntry",
    "FairnessState",
    "FenceRejectedError",
    "JsonCheckpointStore",
    "JsonReferenceStore",
    "Lease",
    "LeaseConflictError",
    "POLICIES",
    "Reservation",
    "RollingTokenPacer",
    "SelectionRecord",
    "SelectionResult",
    "SessionDemand",
    "SimulationMetric",
    "SimulationResult",
    "SimulationScenario",
    "TenantAgentKey",
    "UnpaceableReservationError",
    "build_batch_plan",
    "build_batch_telemetry",
    "build_eligible_frame",
    "calculate_batch_budget",
    "jain_fairness",
    "reserve_with_claim",
    "resolve_batch_window",
    "select_within_agent_grants",
    "simulate_policies",
    "stable_rank_hash",
    "stable_sha256_hex",
    "allocate_hierarchical_tokens",
]
